name: build_deploy
on:
  workflow_dispatch 
jobs:   
  job1: 
    permissions:
      contents: read
      pages: write
      id-token: write
    name: call the reusable workflow
    uses: workflows-and-actions/library/.github/workflows/build_deploy_custom.yml@main
    with:
      build_source: ./
      build_destination: _site
      build_languages: 'ruby python'
      build_script_code: 'jekyll pip_install_requirements'
      deploy_to: gh-pages
      
